# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34f8a58b249cc1e6b5243e4f7ddc71b7a2689a5d9bda9d299a7fc6cfb851d71bf8d6ca7d20106e484a297950f77b98c462661eec46e2a9f61e2a72e88acb2e67

test:
  secret_key_base: ea6bbb7b669cecf7d98a7dc0145ccfae4fa33998846b64be9f2d12b9ccf62311c3d8e1c6fba619c674575d1a5d9eeec50eccd19d7dbe8e584707b8f889f8d9ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
